import { eq } from 'drizzle-orm'
import {
  DOCUMENT_TYPE,
  AUDIT_ACTION,
  AUDIT_ENTITY_TYPE,
  QUALITY_ISSUE_DETAIL_ACTION
} from '../../shared/constants/domain'
import type { createDatabase } from './client'
import { createAuth } from '../lib/auth-config'
import { qualityIssueDetails, qualityIssues, sampleDefects, technicalReports, user } from './schema'
import { recordAuditLog } from '../services/audit-logs'

const DEVELOPMENT_AUTH_SECRET = 'JH6GCnacSZVgpIbeFnyjJVtoGDZEP13r'
const DEVELOPMENT_USER = {
  email: 'qrcc@qdc.com',
  name: 'QRCC User',
  password: 'qwertyuiop'
}
const SEED_SERIAL_NUMBER = 'DEV-SEED-SERIAL-001'
const SEED_DOCUMENT_NUMBER = 'DEV-SEED-TR-001'

type Database = Awaited<ReturnType<typeof createDatabase>>

export interface SeedResult {
  userId: string
  seeded: boolean
}

async function getOrCreateDevelopmentUser(database: Database['db']): Promise<string> {
  const existingUser = await database
    .select({ id: user.id })
    .from(user)
    .where(eq(user.email, DEVELOPMENT_USER.email))
    .limit(1)

  if (existingUser[0]?.id) {
    return existingUser[0].id
  }

  const auth = createAuth(database, {
    baseURL: process.env.BETTER_AUTH_URL ?? 'http://localhost:3000',
    secret: process.env.BETTER_AUTH_SECRET ?? DEVELOPMENT_AUTH_SECRET
  })
  const result = await auth.api.signUpEmail({
    body: DEVELOPMENT_USER,
    headers: new Headers({
      origin: process.env.BETTER_AUTH_URL ?? 'http://localhost:3000'
    })
  })

  return result.user.id
}

export async function seedDatabase(database: Database['db']): Promise<SeedResult> {
  const userId = await getOrCreateDevelopmentUser(database)
  const existingSeed = await database
    .select({ id: qualityIssues.id })
    .from(qualityIssues)
    .where(eq(qualityIssues.serialNumber, SEED_SERIAL_NUMBER))
    .limit(1)

  if (existingSeed[0]?.id) {
    return { userId, seeded: false }
  }

  const now = new Date().toISOString()
  const businessDate = now.slice(0, 10)

  await database.transaction(async (transaction) => {
    const [issue] = await transaction
      .insert(qualityIssues)
      .values({
        issueName: 'Development sample quality issue',
        modelName: 'QDC-DEV-MODEL',
        serialNumber: SEED_SERIAL_NUMBER,
        tanggalKejadian: businessDate,
        notificationNumber: 'DEV-SEED-NOTIFICATION-001',
        detail: 'Data contoh untuk development dan integration testing.',
        keterangan: 'Generated by the development seed.',
        createdAt: now,
        updatedAt: now,
        createdByUserId: userId,
        updatedByUserId: userId
      })
      .returning({ id: qualityIssues.id })

    if (!issue) {
      throw new Error('Development Quality Issue seed gagal dibuat.')
    }

    const [detail] = await transaction
      .insert(qualityIssueDetails)
      .values({
        issueId: issue.id,
        tanggal: now,
        action: QUALITY_ISSUE_DETAIL_ACTION.INITIAL_EVIDENCE,
        remark: 'Initial development timeline entry.',
        createdAt: now,
        updatedAt: now,
        createdByUserId: userId,
        updatedByUserId: userId
      })
      .returning({ id: qualityIssueDetails.id })

    const [sample] = await transaction
      .insert(sampleDefects)
      .values({
        batchId: 'DEV-SEED-BATCH-001',
        issueId: issue.id,
        notificationNumber: 'DEV-SEED-NOTIFICATION-001',
        modelName: 'QDC-DEV-MODEL',
        serialNumber: SEED_SERIAL_NUMBER,
        cabang: 'Development',
        partNumber: 'DEV-PART-001',
        partName: 'Development sample part',
        kerusakanCabang: 'Development sample defect',
        createdAt: now,
        updatedAt: now,
        createdByUserId: userId,
        updatedByUserId: userId
      })
      .returning({ id: sampleDefects.id })

    const [report] = await transaction
      .insert(technicalReports)
      .values({
        issueId: issue.id,
        documentNumber: SEED_DOCUMENT_NUMBER,
        documentType: DOCUMENT_TYPE.TECHNICAL_REPORT,
        releaseDate: businessDate,
        modelName: 'QDC-DEV-MODEL',
        issueName: 'Development sample technical report',
        rootCause: 'Development seed data.',
        action: 'No production action required.',
        createdAt: now,
        updatedAt: now,
        createdByUserId: userId,
        updatedByUserId: userId
      })
      .returning({ id: technicalReports.id })

    if (!detail || !sample || !report) {
      throw new Error('Development related seed gagal dibuat.')
    }

    await recordAuditLog(transaction, {
      entityType: AUDIT_ENTITY_TYPE.QUALITY_ISSUE,
      entityId: issue.id,
      action: AUDIT_ACTION.CREATE,
      actorUserId: userId,
      createdAt: now
    })
    await recordAuditLog(transaction, {
      entityType: AUDIT_ENTITY_TYPE.QUALITY_ISSUE_DETAIL,
      entityId: detail.id,
      action: AUDIT_ACTION.CREATE,
      actorUserId: userId,
      createdAt: now
    })
    await recordAuditLog(transaction, {
      entityType: AUDIT_ENTITY_TYPE.SAMPLE_DEFECT,
      entityId: sample.id,
      action: AUDIT_ACTION.CREATE,
      actorUserId: userId,
      createdAt: now
    })
    await recordAuditLog(transaction, {
      entityType: AUDIT_ENTITY_TYPE.TECHNICAL_REPORT,
      entityId: report.id,
      action: AUDIT_ACTION.CREATE,
      actorUserId: userId,
      createdAt: now
    })
  })

  return { userId, seeded: true }
}

export const developmentSeed = {
  userEmail: DEVELOPMENT_USER.email,
  serialNumber: SEED_SERIAL_NUMBER,
  documentNumber: SEED_DOCUMENT_NUMBER
}
